/// ASL curriculum gloss overrides and verb inventory (LifePrint, HandsSpeak, ASLdeafined).
abstract final class AslCoreLexicon {
  /// Gloss labels that differ from naive uppercase English.
  static const glossOverrides = <String, String>{
    'hi': 'HELLO',
    'hello': 'HELLO',
    'thanks': 'THANK-YOU',
    'thank': 'THANK-YOU',
    'goodbye': 'GOODBYE',
    'bye': 'GOODBYE',
    'everything': 'ALL',
    'all': 'ALL',
    'looking': 'LOOK',
    'look': 'LOOK',
    'are': 'YOU',
    'ok': 'OK',
    'okay': 'OK',
    'mr': 'MR',
    'mrs': 'MRS',
    'ms': 'MS',
    'dr': 'DR',
    'tv': 'TV',
    'ix': 'IX',
    'ix-a': 'IX-a',
    'ix-b': 'IX-b',
    'ix-c': 'IX-c',
    'ix-d': 'IX-d',
    'not': 'NOT',
    'finish': 'FINISH',
    'will': 'WILL',
    'name': 'NAME',
    'this': 'THIS',
    'that': 'THAT',
    'because': 'REASON',
    'something': 'SOMETHING',
    'someone': 'SOMEONE',
    'nothing': 'NOTHING',
    'everyone': 'EVERYONE',
    'everybody': 'EVERYONE',
    'newborn': 'BABY',
    'online': 'ONLINE',
    'smartphone': 'PHONE',
    'smartphones': 'PHONE',
    'timeline': 'TIME',
    'attendees': 'PEOPLE',
  };

  /// Corpus vocabulary: compounds, acronyms, and terms missing from the English dictionary.
  static const corpusGlosses = <String, String>{
    'app': 'APP',
    'apps': 'APP',
    'api': 'API',
    'ott': 'OTT',
    'eco': 'ECO',
    'fi': 'FI',
    'sci': 'SCI',
    'json': 'JSON',
    'png': 'PNG',
    'svg': 'SVG',
    'csv': 'CSV',
    'flexbox': 'FLEXBOX',
    'mockups': 'MOCKUP',
    'mockup': 'MOCKUP',
    'wireframes': 'WIREFRAME',
    'wireframe': 'WIREFRAME',
    'popups': 'POPUP',
    'popup': 'POPUP',
    'verified': 'VERIFIED',
    'verify': 'VERIFY',
    'worldwide': 'WORLDWIDE',
    'archeologists': 'ARCHAEOLOGY',
    'archeologist': 'ARCHAEOLOGY',
    'archaeologists': 'ARCHAEOLOGY',
    'archaeologist': 'ARCHAEOLOGY',
    'boutique': 'BOUTIQUE',
    'boutiques': 'BOUTIQUE',
    'hypermarket': 'STORE',
    'hypermarkets': 'STORE',
    'healthcare': 'HEALTH',
    'gridlock': 'GRIDLOCK',
    'ridesharing': 'RIDE-SHARE',
    'began': 'BEGIN',
    'backpacker': 'BACKPACK',
    'backpackers': 'BACKPACK',
    'cyberbullying': 'CYBERBULLY',
    'screenwriting': 'SCREENWRITE',
    'soundtrack': 'SOUNDTRACK',
    'soundtracks': 'SOUNDTRACK',
    'workspace': 'WORKSPACE',
    'workspaces': 'WORKSPACE',
    'emoji': 'EMOJI',
    'emojis': 'EMOJI',
    'downtime': 'DOWNTIME',
    'multimedia': 'MULTIMEDIA',
    'website': 'WEBSITE',
    'websites': 'WEBSITE',
    'conglomeration': 'GROUP',
    'offline': 'OFFLINE',
    'indie': 'INDIE',
    'database': 'DATABASE',
    'buses': 'BUS',
    'epidemiologists': 'SCIENCE',
    'epidemiologist': 'SCIENCE',
    'stumbling': 'STUMBLE',
    'microchip': 'CHIP',
    'microchips': 'CHIP',
    'troubleshooting': 'FIX',
    'glitch': 'GLITCH',
    'glitches': 'GLITCH',
    'caffeinated': 'COFFEE',
    'caffeine': 'COFFEE',
    'timeframe': 'TIME',
    'lifestyle': 'LIFE',
    'lifestyles': 'LIFE',
    'ostentatious': 'SHOW',
    'rainforests': 'FOREST',
    'rainforest': 'FOREST',
    'breathtaking': 'AMAZING',
    'classify': 'CLASSIFY',
    'customize': 'CUSTOMIZE',
    'debug': 'DEBUG',
    'debugs': 'DEBUG',
    'gridlines': 'GRID',
    'refactor': 'FIX',
    'avatar': 'AVATAR',
    'inbox': 'EMAIL',
    'pdf': 'PDF',
    'ips': 'IP',
    'gps': 'GPS',
    'wav': 'AUDIO',
    'dropoff': 'DROP',
    'intro': 'INTRO',
    'ads': 'AD',
    'mudslide': 'MUDSLIDE',
    'coordinator': 'COORDINATE',
    'coordinators': 'COORDINATE',
    'backpacking': 'BACKPACK',
    'sightseeing': 'SIGHTSEE',
    'beachfront': 'BEACH',
    'sustainability': 'SUSTAIN',
    'checkins': 'CHECK',
    'checkin': 'CHECK',
    'check-in': 'CHECK',
    'check-ins': 'CHECK',
    'eco-friendly': 'ECO',
    'sci-fi': 'SCI-FI',
    'km/l': 'KM',
    'cappuccino': 'COFFEE',
    'espresso': 'ESPRESSO',
    'gate': 'GATE',
    'suitcase': 'SUITCASE',
    'carousel': 'CAROUSEL',
    'voucher': 'VOUCHER',
    'airline': 'AIRLINE',
    'connect': 'CONNECT',
    'connecting': 'CONNECT',
    'number': 'NUMBER',
    'pain': 'PAIN',
    'catch': 'CATCH',
    'locate': 'FIND',
    'scan': 'SCAN',
    'delay': 'DELAY',
    'worse': 'WORSE',
    'drink': 'DRINK',
    'fill': 'FILL',
    'printed': 'PRINT',
    'leave': 'LEAVE',
    'fast': 'FAST',
    'times': 'TIME',
    'prescribe': 'PRESCRIBE',
    'yeah': 'YES',
    'ai': 'AI',
    'percent': 'PERCENT',
    'coorg': 'COORG',
    'reason': 'REASON',
    'if': 'IF',
    'during': 'DURING',
    'out': 'OUT',
    'train': 'TRAIN',
    'minute': 'MINUTE',
    'minutes': 'MINUTE',
    'five': 'FIVE',
    'flight': 'FLIGHT',
    'three-times': 'THREE-TIMES',
    'cafe': 'CAFE',
    'barista': 'BARISTA',
    'croissant': 'CROISSANT',
    'croissants': 'CROISSANT',
    'phobia': 'PHOBIA',
    'checkpoint': 'CHECKPOINT',
    'tea': 'TEA',
    'pastry': 'PASTRY',
    'bakery': 'BAKERY',
    'entrance': 'ENTRANCE',
    'awful': 'AWFUL',
    'bitter': 'BITTER',
    'server': 'SERVER',
    'oat': 'OAT',
    'dairy': 'DAIRY',
    'discount': 'DISCOUNT',
    'refund': 'REFUND',
    'ceramic': 'CERAMIC',
    'mug': 'MUG',
    'breakfast': 'BREAKFAST',
    'stomach': 'STOMACH',
    'van': 'VAN',
    'indoor': 'INDOOR',
    'fan': 'FAN',
    'broke': 'BREAK',
    'broken': 'BROKEN',
    'disconnect': 'DISCONNECT',
    'chocolate': 'CHOCOLATE',
    'chest': 'CHEST',
    'dizzy': 'DIZZY',
    'medicine': 'MEDICINE',
    'bottle': 'BOTTLE',
    'laboratory': 'LAB',
    'lab': 'LAB',
    'knee': 'KNEE',
    'surgery': 'SURGERY',
    'surgeon': 'SURGEON',
    'authorization': 'AUTHORIZATION',
    'ambulance': 'AMBULANCE',
    'throat': 'THROAT',
    'fever': 'FEVER',
    'needle': 'NEEDLE',
    'injection': 'INJECTION',
    'thermometer': 'THERMOMETER',
    'dust': 'DUST',
    'pharmacist': 'PHARMACIST',
    'dentist': 'DENTIST',
    'teeth': 'TEETH',
    'boarding': 'BOARDING',
    'kiosk': 'KIOSK',
    'digital': 'DIGITAL',
    'luggage': 'LUGGAGE',
    'kilogram': 'KG',
    'kilograms': 'KG',
    'kg': 'KG',
    'confiscate': 'TAKE-AWAY',
    'confiscated': 'TAKE-AWAY',
    'vacation': 'VACATION',
    'highway': 'HIGHWAY',
    'internationally': 'INTERNATIONAL',
    'runway': 'RUNWAY',
    'tarmac': 'TARMAC',
    'economy': 'ECONOMY',
    'pillow': 'PILLOW',
    'neck': 'NECK',
    'uncomfortable': 'UNCOMFORTABLE',
    'blizzard': 'BLIZZARD',
    'fragile': 'FRAGILE',
    'camera': 'CAMERA',
    'cargo': 'CARGO',
    'lounge': 'LOUNGE',
    'chaotic': 'ROWDY',
    'visa': 'VISA',
    'expired': 'EXPIRED',
    'detain': 'STOP',
    'automated': 'AUTOMATED',
    'scanner': 'SCANNER',
    'scanning': 'SCANNER',
    'provided': 'PROVIDED',
    'lunch': 'LUNCH',
    'contains': 'INSIDE',
    'dashboard': 'DASHBOARD',
    'shear': 'DANGER',
    'wind': 'WIND',
    'abort': 'STOP',
    'takeoff': 'TAKEOFF',
    'captain': 'CAPTAIN',
    'wallet': 'WALLET',
    'leather': 'LEATHER',
    'stitching': 'THREAD',
    'thread': 'THREAD',
    'jacket': 'JACKET',
    'perfume': 'PERFUME',
    'crystal': 'CRYSTAL',
    'clumsy': 'SHOPPER',
    'shopper': 'SHOPPER',
    'mall': 'MALL',
    'retail': 'RETAIL',
    'coupon': 'COUPON',
    'valid': 'VALID',
    'cashier': 'CASHIER',
    'storefront': 'STOREFRONT',
    'marble': 'MARBLE',
    'shiny': 'SHINY',
    'expiration': 'EXPIRATION',
    'silk': 'SILK',
    'tissue': 'TISSUE',
    'commuter': 'COMMUTER',
    'locomotive': 'LOCOMOTIVE',
    'cone': 'CONE',
    'bench': 'BENCH',
    'itinerary': 'SCHEDULE',
    'politely': 'POLITE',
    'scraped': 'SCRAP',
    'scrape': 'SCRAP',
    'turnstile': 'TURNSTILE',
    'duffel': 'DUFFEL',
    'puddle': 'PUDDLE',
    'muddy': 'MUDDY',
    'shelter': 'SHELTER',
    'not-can': 'NOT-CAN',
    'pass-me': 'PASS-ME',
    'wake-up': 'WAKE-UP',
    'tear-open': 'TEAR-OPEN',
    'too-much': 'TOO-MUCH',
    'take-away': 'TAKE-AWAY',
    'two-pieces': 'TWO-PIECES',
    'jump-over': 'JUMP-OVER',
    'write-wrong': 'WRITE-WRONG',
    'pass': 'PASS',
    'put': 'PUT',
    'hit': 'HIT',
    'drop': 'DROP',
    'bring': 'BRING',
    'smash': 'SMASH',
    'crack': 'CRACK',
    'scratch': 'SCRATCH',
    'postpone': 'POSTPONE',
    'mislabel': 'WRITE-WRONG',
    'mislabeled': 'WRITE-WRONG',
    'shop': 'SHOP',
    'manager': 'MANAGER',
    'severe': 'SEVERE',
    'severely': 'SEVERE',
    'badly': 'SEVERE',
    'burnt': 'BURN',
    'burned': 'BURN',
    'burn': 'BURN',
    'prefer': 'PREFER',
    'get': 'RECEIVE',
    'receive': 'RECEIVE',
    'show': 'SHOW',
    'own': 'OWN',
    'schedule': 'SCHEDULE',
    'worker': 'WORKER',
    'officer': 'OFFICER',
    'officers': 'OFFICER',
    'handler': 'HANDLER',
    'technician': 'TECHNICIAN',
    'assistant': 'ASSISTANT',
    'patient': 'PATIENT',
    'nurse': 'NURSE',
    'baker': 'BAKER',
    'driver': 'DRIVER',
    'delivery': 'DELIVERY',
    'cleaning': 'CLEAN',
    'crew': 'CREW',
    'twenty': '20',
    'fifty': '50',
    'four': '4',
    'locked': 'GRIDLOCK',
    'rowdy': 'ROWDY',
    'inside': 'INSIDE',
    'freeze': 'FREEZE',
    'freezing': 'FREEZING',
    'polite': 'POLITE',
    'instantly': 'FAST',
    'automatically': 'AUTOMATIC',
    'accidentally': 'ACCIDENT',
    'accident': 'ACCIDENT',
    'missing': 'MISSING',
    'rejected': 'REJECT',
    'reject': 'REJECT',
    'wore': 'WEAR',
    'wear': 'WEAR',
    'stood': 'STAND',
    'stand': 'STAND',
    'sat': 'SIT',
    'sit': 'SIT',
    'woke': 'WAKE-UP',
    'wake': 'WAKE-UP',
    'tore': 'TEAR',
    'tear': 'TEAR',
    'crushed': 'CRUSH',
    'crush': 'CRUSH',
    'swallow': 'SWALLOW',
    'vision': 'VISION',
    'protective': 'PROTECTIVE',
    'masks': 'MASK',
    'mask': 'MASK',
    'signatures': 'SIGNATURE',
    'signature': 'SIGNATURE',
    'records': 'RECORD',
    'record': 'RECORD',
    'papers': 'PAPER',
    'paper': 'PAPER',
    'treatment': 'TREATMENT',
    'plan': 'PLAN',
    'sample': 'SAMPLE',
    'blood': 'BLOOD',
    'refused': 'REFUSE',
    'refuse': 'REFUSE',
    'fear': 'FEAR',
    'deep': 'DEEP',
    'alarm': 'ALARM',
    'emergency': 'EMERGENCY',
    'ring': 'RING',
    'bell': 'BELL',
    'immediately': 'NOW',
    'upset': 'UPSET',
    'products': 'FOOD',
    'product': 'FOOD',
    'sugar': 'SUGAR',
    'sweet': 'SWEET',
    'white': 'WHITE',
    'wrong': 'WRONG',
    'outdoor': 'OUTDOOR',
    'window': 'WINDOW',
    'near': 'NEAR',
    'open': 'OPEN',
    'completely': 'COMPLETELY',
    'outside': 'OUTSIDE',
    'move': 'MOVE',
    'fresh': 'FRESH',
    'hurt': 'HURT',
    'hurts': 'PAIN',
    'dry': 'DRY',
    'large': 'LARGE',
    'pill': 'PILL',
    'pills': 'PILL',
    'metal': 'METAL',
    'gates': 'GATE',
    'storm': 'STORM',
    'rain': 'RAIN',
    'weighs': 'WEIGHT',
    'weigh': 'WEIGHT',
    'extra': 'EXTRA',
    'fee': 'FEES',
    'water': 'WATER',
    'family': 'FAMILY',
    'travel': 'TRAVEL',
    'international': 'INTERNATIONAL',
    'passport': 'PASSPORT',
    'agent': 'AGENT',
    'vehicle': 'VEHICLE',
    'ground': 'GROUND',
    'engine': 'ENGINE',
    'airplane': 'PLANE',
    'expensive': 'EXPENSIVE',
    'seat': 'SEAT',
    'chair': 'SEAT',
    'winter': 'WINTER',
    'strikes': 'HIT',
    'strike': 'HIT',
    'striking': 'HIT',
    'border': 'BORDER',
    'traveler': 'TRAVELER',
    'ticket': 'TICKET',
    'tickets': 'TICKET',
    'pieces': 'TWO-PIECES',
    'piece': 'PIECE',
    'food': 'FOOD',
    'warns': 'WARN',
    'warn': 'WARN',
    'warned': 'WARN',
    'display': 'DISPLAY',
    'under': 'UNDER',
    'lost': 'LOSE',
    'lose': 'LOSE',
    'returned': 'RETURN',
    'return': 'RETURN',
    'gift': 'GIFT',
    'free': 'FREE',
    'spend': 'SPEND',
    'dollars': 'DOLLAR',
    'dollar': 'DOLLAR',
    'money': 'MONEY',
    'television': 'TV',
    'smaller': 'SMALL',
    'screen': 'SCREEN',
    'clothing': 'CLOTHING',
    'brand': 'BRAND',
    'issue': 'GIVE',
    'credit': 'CREDIT',
    'stock': 'STOCK',
    'boy': 'BOY',
    'tags': 'TAG',
    'tag': 'TAG',
    'price': 'PRICE',
    'shoes': 'SHOE',
    'shoe': 'SHOE',
    'electronic': 'ELECTRONIC',
    'audio': 'AUDIO',
    'loud': 'LOUD',
    'steals': 'STEAL',
    'steal': 'STEAL',
    'item': 'ITEM',
    'customer': 'CUSTOMER',
    'client': 'CUSTOMER',
    'purchase': 'BUY',
    'purchased': 'BUY',
    'passed': 'PASS',
    'week': 'WEEK',
    'last': 'PAST',
    'triggers': 'RING',
    'trigger': 'RING',
    'wrapped': 'WRAP',
    'wrap': 'WRAP',
    'dress': 'DRESS',
    'waiting': 'WAIT',
    'delayed': 'DELAY',
    'regular': 'REGULAR',
    'connection': 'CONNECT',
    'connections': 'CONNECT',
    'arrives': 'ARRIVE',
    'arrive': 'ARRIVE',
    'plastic': 'PLASTIC',
    'safety': 'SAFETY',
    'express': 'EXPRESS',
    'passenger': 'PASSENGER',
    'concrete': 'CONCRETE',
    'high-speed': 'FAST',
    'regional': 'STANDARD',
    'standard': 'STANDARD',
    'hours': 'HOUR',
    'hour': 'HOUR',
    'takes': 'TAKE',
    'take': 'TAKE',
    'jumps': 'JUMP-OVER',
    'jump': 'JUMP',
    'jumped': 'JUMP-OVER',
    'closes': 'CLOSE',
    'close': 'CLOSE',
    'platform': 'PLATFORM',
    'brick': 'BRICK',
    'weather': 'WEATHER',
    'incredibly': 'AWFUL',
    'hot': 'HOT',
    'cold': 'COLD',
    'tastes': 'TASTE',
    'taste': 'TASTE',
    'tasting': 'TASTE',
    'placed': 'PUT',
    'place': 'PUT',
    'results': 'REPORT',
    'result': 'REPORT',
    'operation': 'SURGERY',
    'postponed': 'POSTPONE',
    'damaged': 'DAMAGE',
    'damage': 'DAMAGE',
    'feels': 'FEEL',
    'feel': 'FEEL',
    'change': 'CHANGE',
    'changed': 'CHANGE',
    'dropped': 'DROP',
    'cleaned': 'CLEAN',
    'clean': 'CLEAN',
    'quickly': 'QUICK',
    'quick': 'QUICK',
    'afternoon': 'AFTERNOON',
    'morning': 'MORNING',
    'yesterday': 'YESTERDAY',
    'room': 'ROOM',
    'glass': 'GLASS',
    'break': 'BROKEN',
    'air': 'AIR',
    'full': 'FULL',
    'order': 'ORDER',
    'orders': 'ORDER',
    'rejects': 'REJECT',
    'sign': 'SIGN',
    'signed': 'SIGN',
    'medical': 'MEDICAL',
    'clinic': 'CLINIC',
    'hospital': 'HOSPITAL',
    'doctor': 'DOCTOR',
    'doctors': 'DOCTOR',
    'needles': 'NEEDLE',
    'test': 'TEST',
    'tests': 'TEST',
    'tooth': 'TOOTH',
    'this': 'THIS',
    'today': 'TODAY',
    'work': 'WORK',
    'director': 'MANAGER',
    'time': 'TIME',
    'three': 'THREE',
    'phone': 'PHONE',
    'telephone': 'PHONE',
    'call': 'CALL',
    'called': 'CALL',
    'calling': 'CALL',
    'find': 'FIND',
    'found': 'FIND',
    'finding': 'FIND',
    'cannot': 'CANNOT',
    'cant': 'NOT-CAN',
    'starbucks': 'CAFE',
    'coffee': 'COFFEE',
    'milk': 'MILK',
    'tongue': 'TONGUE',
    'receipt': 'RECEIPT',
    'cash': 'CASH',
    'want': 'WANT',
    'wanted': 'WANT',
    'wanting': 'WANT',
    'must': 'MUST',
    'need': 'NEED',
    'needed': 'NEED',
    'needs': 'NEED',
    'needing': 'NEED',
    'see': 'SEE',
    'seeing': 'SEE',
    'saw': 'SEE',
    'seen': 'SEE',
    'now': 'NOW',
    'spontaneous': 'NOW',
    'headache': 'HEADACHE',
    'breathe': 'CHEST',
    'brought': 'BRING',
    'bringing': 'BRING',
    'pie': 'PASTRY',
    'serve': 'SERVER',
    'served': 'SERVER',
    'losing': 'LOSE',
    'impact': 'HIT',
    'hitting': 'HIT',
    'house': 'HOUSE',
    'standing': 'STAND',
    'terminal': 'TERMINAL',
    'both': '2',
    'two': '2',
    'master': 'MASTER',
    'station': 'STATION',
    'print': 'PRINT',
    'printing': 'PRINT',
    'ask': 'ASK',
    'asked': 'ASK',
    'asking': 'ASK',
    'scrap': 'SCRAP',
    'scraping': 'SCRAP',
    'bought': 'BUY',
    'buy': 'BUY',
    'buying': 'BUY',
    'high': 'HIGH',
    'speed': 'FAST',
    'trains': 'TRAIN',
    'security': 'SECURITY',
    'someone': 'PERSON',
    'person': 'PERSON',
    'all_of_sudden': 'FAST',
    'close-door': 'CLOSE',
    'closed': 'CLOSED',
    'closing': 'CLOSE',
    'bag': 'BAG',
    'bags': 'BAG',
    'iron': 'IRON',
    'heavy': 'HEAVY',
    'tracks': 'TRACK',
    'track': 'TRACK',
    'sun': 'SUN',
    'made': 'MAKE',
    'make': 'MAKE',
    'making': 'MAKE',
    'missed': 'MISSED',
    'miss': 'MISSED',
    'late': 'LATE',
    'arrived': 'ARRIVE',
    'bus': 'BUS',
    'wait': 'WAIT',
    'waited': 'WAIT',
    'news': 'NEWS',
    'stuck': 'STUCK',
    'traffic': 'TRAFFIC',
    'bicycle': 'BIKE',
    'biking': 'BIKE',
    'riding': 'RIDE',
    'vegetarian': 'VEGETARIAN',
    'gluten-free': 'GLUTEN-FREE',
    'glutenfree': 'GLUTEN-FREE',
    'spaghetti': 'SPAGHETTI',
    'garlic': 'GARLIC',
    'popcorn': 'POPCORN',
    'peanut': 'PEANUT',
    'peanuts': 'PEANUTS',
    'dehydrated': 'DEHYDRATED',
    'coworker': 'CO-WORKER',
    'thunderstorm': 'THUNDERSTORM',
    'marshmallow': 'MARSHMALLOW',
    'treadmill': 'TREADMILL',
    'marathon': 'MARATHON',
    'groceries': 'GROCERIES',
    'grocery': 'GROCERY',
    'oversleep': 'OVERSLEEP',
    'interpreter': 'INTERPRETER',
    'graduation': 'GRADUATION',
    'vacuum': 'VACUUM',
    'umbrella': 'UMBRELLA',
    'rainbow': 'RAINBOW',
    'garbage': 'GARBAGE',
    'champion': 'CHAMPION',
    'cinema': 'CINEMA',
    'allergy': 'ALLERGY',
    'pharmacy': 'PHARMACY',
    'swollen': 'SWELLING',
    'swelling': 'SWELLING',
    'wifi': 'WI-FI',
    'spam': 'SPAM',
    'charger': 'CHARGER',
    'dessert': 'DESSERT',
    'desserts': 'DESSERT',
    'wing': 'WING',
    'wings': 'WING',
    'famous': 'FAMOUS',
    'spicy': 'SPICY',
    'reserve': 'RESERVE',
    'service': 'SERVICE',
    'crowded': 'CROWDED',
    'rush': 'RUSH',
    'baggage': 'BAGGAGE',
    'elevator': 'ELEVATOR',
    'couch': 'COUCH',
    'stretch': 'STRETCH',
    'sugars': 'SUGAR',
    'iced': 'COLD-BREW',
    'cold-brew': 'COLD-BREW',
    'oat-milk': 'OAT-MILK',
    'credit-card': 'CREDIT-CARD',
    'creditcard': 'CREDIT-CARD',
    'new-york': 'NEW-YORK',
    'newyork': 'NEW-YORK',
    'excuse-me': 'EXCUSE-ME',
    'text-me': 'TEXT-ME',
    'go-there': 'GO-THERE',
    'help-me': 'HELP-ME',
    'for-me': 'FOR-ME',
    'call-me': 'CALL-ME',
    'send-back': 'SEND-BACK',
    'move-here': 'MOVE-HERE',
    'all-night': 'ALL-NIGHT',
    'all-day': 'ALL-DAY',
    'look-at': 'LOOK-AT',
    'two-times': 'TWO TIMES',
    'clean-all': 'CLEAN-ALL',
    'cover-all': 'COVER-ALL',
    'knock-over': 'KNOCK-OVER',
    'cool-down': 'COOL-DOWN',
    'clap-loud': 'CLAP-LOUD',
    'try-on': 'TRY-ON',
    'fly-here': 'FLY-HERE',
    'leave-behind': 'LEAVE-BEHIND',
    'locked-out': 'LOCKED-OUT',
    'not-allow': 'NOT-ALLOW',
    'next-to-you': 'NEXT-TO-YOU',
    'years-old': 'YEARS-OLD',
    'one-oclock': '1-O\'CLOCK',
    'two-oclock': '2-O\'CLOCK',
    'three-oclock': '3-O\'CLOCK',
    'four-oclock': '4-O\'CLOCK',
    'five-oclock': '5-O\'CLOCK',
    'six-oclock': 'SIX-O\'CLOCK',
    'seven-oclock': 'SEVEN-O\'CLOCK',
    'eight-oclock': '8-O\'CLOCK',
    'nine-oclock': '9-O\'CLOCK',
    '1-oclock': '1-O\'CLOCK',
    '2-oclock': '2-O\'CLOCK',
    '3-oclock': '3-O\'CLOCK',
    '4-oclock': '4-O\'CLOCK',
    '5-oclock': '5-O\'CLOCK',
    '8-oclock': '8-O\'CLOCK',
    '9-oclock': '9-O\'CLOCK',
    'one-years-old': '1-YEARS-OLD',
    'two-years-old': '2-YEARS-OLD',
    'three-years-old': '3-YEARS-OLD',
    'four-years-old': '4-YEARS-OLD',
    'five-years-old': '5-YEARS-OLD',
    'six-years-old': '6-YEARS-OLD',
    'seven-years-old': '7-YEARS-OLD',
    'eight-years-old': '8-YEARS-OLD',
    'nine-years-old': '9-YEARS-OLD',
    '1-years-old': '1-YEARS-OLD',
    '2-years-old': '2-YEARS-OLD',
    '3-years-old': '3-YEARS-OLD',
    '4-years-old': '4-YEARS-OLD',
    '5-years-old': '5-YEARS-OLD',
    '6-years-old': '6-YEARS-OLD',
    '7-years-old': '7-YEARS-OLD',
    '8-years-old': '8-YEARS-OLD',
    '9-years-old': '9-YEARS-OLD',
    'one-weeks-ago': '1-WEEKS-AGO',
    'two-weeks-ago': '2-WEEKS-AGO',
    'three-weeks-ago': '3-WEEKS-AGO',
    'four-weeks-ago': '4-WEEKS-AGO',
    'five-weeks-ago': '5-WEEKS-AGO',
    'six-weeks-ago': '6-WEEKS-AGO',
    'seven-weeks-ago': '7-WEEKS-AGO',
    'eight-weeks-ago': '8-WEEKS-AGO',
    'nine-weeks-ago': '9-WEEKS-AGO',
    '3-weeks-ago': '3-WEEKS-AGO',
    '2-weeks-ago': '2-WEEKS-AGO',
    'two-days': '2-DAYS',
    'three-days': '3-DAYS',
    'four-days': '4-DAYS',
    'five-days': '5-DAYS',
    'two-years': '2-YEARS',
    'three-years': '3-YEARS',
    'four-years': '4-YEARS',
    'five-years': '5-YEARS',
    'six-years': '6-YEARS',
    'seven-years': '7-YEARS',
    'eight-years': '8-YEARS',
    'nine-years': '9-YEARS',
    '2-days': '2-DAYS',
    '5-years': '5-YEARS',
    'point-there': 'POINT-THERE',
    'point-there-plural': 'POINT-THERE-PLURAL',
    'book-on': 'BOOK-ON',
    'book-under': 'BOOK-UNDER',
    'book-in': 'BOOK-IN',
    'phone-on-top': 'PHONE-ON-TOP',
    'book-on-top': 'BOOK-ON-TOP',
    'how-many': 'HOW-MANY',
    'how-much': 'HOW-MUCH',
    'deep/far': 'DEEP/FAR',
    'will-be': 'WILL-BE',
    'chai': 'CHAI',
    'samosa': 'SAMOSA',
    'dosa': 'DOSA',
    'spoiled': 'SPOILED',
    'siblings': 'SIBLINGS',
    'brothers': 'BROTHERS',
    'married': 'MARRIED',
    'birthday': 'BIRTHDAY',
    'railway': 'RAILWAY',
    'injury': 'INJURY',
    'xerox': 'XEROX',
    'aadhaar': 'AADHAAR',
    'stolen': 'STOLEN',
    'withdraw': 'WITHDRAW',
    'vegetables': 'VEGETABLES',
    'happening': 'HAPPENING',
    'blowing': 'BLOWING',
    'sunlight': 'SUNLIGHT',
    'dripping': 'DRIPPING',
    'electricity': 'ELECTRICITY',
    'trivandrum': 'TRIVANDRUM',
    'madurai': 'MADURAI',
    'email': 'EMAIL',
    'fees': 'FEES',
    'isl': 'ISL',
    'notes': 'NOTES',
    'note': 'NOTES',
    'marks': 'MARKS',
    'sibling': 'SIBLINGS',
    'meeting': 'MEETING',
    '10-o\'clock': "10-O'CLOCK",
    'atm': 'ATM',
    'nam': 'NAME',
    'naam': 'NAME',
    'dont': 'DON\'T',
    "don't": 'DON\'T',
    'clouds': 'CLOUDS',
    'clothes': 'CLOTHES',
    'gone': 'GONE',
    '1-day': '1-DAY',
    '2-day': '2-DAY',
    '3-day': '3-DAY',
    '4-day': '4-DAY',
    '5-day': '5-DAY',
    '6-day': '6-DAY',
    '7-day': '7-DAY',
    '8-day': '8-DAY',
    '9-day': '9-DAY',
    'one-day': '1-DAY',
    'two-day': '2-DAY',
    'three-day': '3-DAY',
    'bengaluru': 'BENGALURU',
    'bangalore': 'BENGALURU',
    'mumbai': 'MUMBAI',
    'bombay': 'MUMBAI',
    'delhi': 'DELHI',
    'new-delhi': 'DELHI',
    'chennai': 'CHENNAI',
    'madras': 'CHENNAI',
    'kolkata': 'KOLKATA',
    'calcutta': 'KOLKATA',
    'hyderabad': 'HYDERABAD',
    'pune': 'PUNE',
    'jaipur': 'JAIPUR',
    'ahmedabad': 'AHMEDABAD',
    'kochi': 'KOCHI',
    'cochin': 'KOCHI',
    'hr': 'HR',
    'bin': 'BIN',
    'occupy': 'OCCUPIED',
    'occupied': 'OCCUPIED',
    'taken': 'OCCUPIED',
    'mountain': 'MOUNTAIN',
    'mountains': 'MOUNTAIN',
    'weekend': 'WEEKEND',
    'rent': 'RENT',
    'taxi': 'TAXI',
    'battery': 'BATTERY',
    'apartment': 'APARTMENT',
    'shower': 'SHOWER',
    'blank': 'BLANK',
    'microphone': 'MICROPHONE',
    'mute': 'MUTE',
    'workout': 'WORKOUT',
    'dying': 'DYING',
    'vet': 'VET',
    'grandmother': 'GRANDMOTHER',
    'promotion': 'PROMOTION',
    'contract': 'CONTRACT',
    'humid': 'HUMID',
    'autumn': 'AUTUMN',
    'concert': 'CONCERT',
    'canvas': 'CANVAS',
    'watercolor': 'WATERCOLOR',
    'soccer': 'SOCCER',
    'guitar': 'GUITAR',
    'camping': 'CAMPING',
    'comic': 'COMIC',
    'jeans': 'JEANS',
    'sweater': 'SWEATER',
    'wedding': 'WEDDING',
    'hassle': 'HASSLE',
    'professor': 'PROFESSOR',
    'literature': 'LITERATURE',
    'biology': 'BIOLOGY',
    'textbook': 'TEXTBOOK',
    'relieved': 'RELIEVED',
    'quiet': 'QUIET',
    'silent': 'SILENT',
    'certified': 'CERTIFIED',
    'stage': 'STAGE',
    'delicious': 'DELICIOUS',
    'salty': 'SALTY',
    'allergic': 'ALLERGIC',
    'snowstorm': 'SNOW-STORM',
    'snow-storm': 'SNOW-STORM',
    'give-you': '1-GIVE-YOU',
    'give-me': 'GIVE-ME',
    'tell-you': 'TELL-YOU',
    'tell-me': 'TELL-ME',
    'cancel': 'CANCEL',
    'cancelled': 'CANCEL',
    'canceled': 'CANCEL',
    'store': 'STORE',
  };

  /// English words where ASL-LEX maps a different concept (e.g. check→PAY).
  /// Used for grammar-teaching glosses; certified lexicon wins otherwise.
  static const pedagogicalOverrides = <String, String>{
    'check': 'CHECK',
    'do': 'DO',
    // ASL-LEX maps social verbs to unrelated certified glosses.
    'meet': 'MEET',
    'see': 'SEE',
    'later': 'LATER',
    'welcome': 'WELCOME',
    'baby': 'BABY',
    'fill': 'FILL',
    'catch': 'CATCH',
    'pain': 'PAIN',
    'drink': 'DRINK',
    'gate': 'GATE',
    'call': 'CALL',
    'prefer': 'PREFER',
    'burn': 'BURN',
    'cafe': 'CAFE',
    'tea': 'TEA',
    'barista': 'BARISTA',
    'phobia': 'PHOBIA',
    'show': 'SHOW',
    'get': 'RECEIVE',
    'put': 'PUT',
    'shop': 'SHOP',
    'card': 'CARD',
  };

  static const pedagogicalIds = <String, String>{
    'check': 'check',
    'do': 'do',
    'meet': 'meet',
    'see': 'see',
    'later': 'later',
    'welcome': 'welcome',
    'baby': 'baby',
  };

  /// Avatar pose ids for signs with stable animation keys.
  static const idOverrides = <String, String>{
    'hi': 'hello',
    'hello': 'hello',
    'thanks': 'thank_you',
    'thank': 'thank_you',
    'looking': 'looking',
    'look': 'looking',
    'are': 'you',
    'you': 'you',
    'how': 'how',
    'today': 'today',
    'please': 'please',
    'help': 'help',
    'yes': 'yes',
    'no': 'no',
    'name': 'name',
    'my': 'my',
    'this': 'this',
    'that': 'that',
    'good': 'good',
  };

  /// High-frequency ASL verbs (ASL 1–4 / LifePrint units) beyond grammar engine stems.
  static const curriculumVerbs = {
    'accept',
    'agree',
    'answer',
    'apologize',
    'ask',
    'attend',
    'believe',
    'borrow',
    'bring',
    'build',
    'buy',
    'call',
    'carry',
    'celebrate',
    'change',
    'choose',
    'clean',
    'close',
    'cook',
    'count',
    'cry',
    'cut',
    'dance',
    'decide',
    'describe',
    'discuss',
    'disturb',
    'draw',
    'drive',
    'eat',
    'explain',
    'feel',
    'find',
    'finish',
    'fix',
    'fly',
    'forget',
    'hear',
    'help',
    'happen',
    'hope',
    'imagine',
    'invite',
    'join',
    'keep',
    'know',
    'laugh',
    'learn',
    'leave',
    'like',
    'lie',
    'listen',
    'live',
    'lose',
    'love',
    'make',
    'meet',
    'move',
    'need',
    'open',
    'pay',
    'plan',
    'play',
    'prefer',
    'promise',
    'read',
    'remember',
    'run',
    'say',
    'see',
    'sell',
    'send',
    'show',
    'sing',
    'sit',
    'sleep',
    'smile',
    'speak',
    'stand',
    'start',
    'stay',
    'stop',
    'study',
    'swim',
    'take',
    'talk',
    'teach',
    'tell',
    'thank',
    'think',
    'try',
    'turn',
    'understand',
    'use',
    'visit',
    'wait',
    'walk',
    'wash',
    'want',
    'wear',
    'win',
    'wish',
    'work',
    'write',
    'share',
    'gather',
    'drop',
    'hit',
    'put',
    'smash',
    'crack',
    'scratch',
    'scrape',
    'crush',
    'burn',
    'ring',
    'wrap',
    'tear',
    'reject',
    'postpone',
    'damage',
    'print',
    'disconnect',
    'steal',
    'lock',
    'detain',
    'swallow',
    'return',
    'deal',
    'present',
    'repair',
    'rebuild',
    'organize',
    'demonstrate',
    'generate',
    'anticipate',
    'accommodate',
    'alienate',
    'extrapolate',
    'oscillate',
    'terminate',
    'contemplate',
    'illuminate',
    'duplicate',
    'formulate',
    'validate',
    'compensate',
    'accelerate',
    'execute',
    'decorate',
    'simulate',
    'deteriorate',
    'facilitate',
    'emphasize',
    'eliminate',
    'integrate',
    'scrutinize',
    'cultivate',
    'dominate',
    'imitate',
    'motivate',
    'fluctuate',
    'jeopardize',
    'prepare',
    'sadden',
    'coordinate',
    'begin',
    'stumble',
    'worry',
  };

  /// Common adjective suffixes (LifePrint subject + adjective: HE TALL).
  static const adjectiveSuffixes = [
    'ous',
    'ful',
    'less',
    'ive',
    'ent',
    'ant',
    'able',
    'ible',
    'al',
    'ic',
    'ish',
    'like',
    'some',
    'est',
  ];
}
