abstract final class IslSpokenCorpus {
  static const hindiPhrases = {
    'मुझे एक कप चाय चाहिए।': 'me one cup chai want',
    'क्या आपके पास शाकाहारी खाना है?': 'vegetarian food have you',
    'खाना बहुत तीखा है।': 'food spicy very',
    'कृपया बिल ले आइए।': 'bill bring please',
    'मैंने आज दोपहर का खाना नहीं खाया।': 'today lunch me eat not',
    'पानी ठंडा है या गर्म?': 'water cold hot which',
    'मुझे समोसा पसंद है।': 'me samosa like',
    'रसोई में चीनी कहाँ है?': 'kitchen sugar where',
    'कल हम रेस्तरां जाएंगे।': 'tomorrow we restaurant go',
    'खाना खराब हो गया है।': 'food spoiled',
    'आपका नाम क्या है?': 'your name what',
    'तुम्हारा नाम क्या है?': 'your name what',
    'तुमारा नाम क्या है?': 'your name what',
    'tumara nam kya hai': 'your name what',
    'tumhara nam kya hai': 'your name what',
    'tumhara naam kya hai': 'your name what',
    'tumara naam kya hai': 'your name what',
    'aapka nam kya hai': 'your name what',
    'apka nam kya hai': 'your name what',
    'aapka naam kya hai': 'your name what',
    'मेरा नाम राहुल है।': 'my name fs-rahul',
    'आपके कितने भाई-बहन हैं?': 'your siblings how-many',
    'मेरी माँ शिक्षिका हैं।': 'my mother teacher',
    'यह मेरा छोटा भाई है।': 'this my brother small',
    'आप कहाँ रहते हैं?': 'you live where',
    'मैं दिल्ली में रहता हूँ।': 'me delhi live',
    'क्या आप शादीशुदा हैं?': 'you married',
    'आज मेरे दोस्त का जन्मदिन है।': 'today my friend birthday',
    'मेरे पिता कल आए थे।': 'yesterday my father arrive',
    'रेलवे स्टेशन कहाँ है?': 'railway station where',
    'दिल्ली की ट्रेन कब आएगी?': 'delhi train arrive when',
    'मुझे एक ऑटो चाहिए।': 'me auto need',
    'टिकट की कीमत कितनी है?': 'ticket cost how-much',
    'बस छूट गई।': 'bus missed',
    'रास्ता बहुत खराब है।': 'road bad very',
    'एयरपोर्ट यहाँ से दूर है।': 'airport here from deep/far',
    'क्या यह बस मुंबई जाती है?': 'this bus mumbai go',
    'मेरी कार खराब हो गई है।': 'my car broken',
    'मुझे खिड़की वाली सीट चाहिए।': 'me window seat want',
    'मेरे पेट में दर्द है।': 'my stomach hurt',
    'डॉक्टर कब आएंगे?': 'doctor arrive when',
    'मुझे तेज़ बुखार है।': 'me fever high',
    'अस्पताल कहाँ है?': 'hospital where',
    'दवा दिन में दो बार लेनी है।': 'medicine day two times take',
    'मुझे चक्कर आ रहे हैं।': 'me dizzy',
    'एम्बुलेंस को बुलाओ!': 'ambulance call quick',
    'क्या मुझे चोट लगी है?': 'me injury have',
    'मेरा पैर सूज गया है।': 'my leg swelling',
    'मुझे खून की जांच करानी है।': 'me blood test need',
    'मैनेजर कहाँ हैं?': 'manager where',
    'कल मीटिंग सुबह १० बजे है।': 'tomorrow meeting morning 10-o\'clock',
    'मुझे बहुत काम है।': 'me work much',
    'कंप्यूटर काम नहीं कर रहा है।': 'computer work not',
    'आज मेरी छुट्टी है।': 'today my holiday',
    'कृपया इस पेपर पर हस्ताक्षर करें।': 'this paper sign please',
    'इंटरव्यू अच्छा रहा।': 'interview good',
    'मुझे ईमेल भेजें।': 'me email send',
    'ऑफिस शनिवार को बंद रहता है।': 'office saturday closed',
    'मुझे सैलरी मिल गई।': 'me salary receive',
    'स्कूल कब खुलेगा?': 'school open when',
    'मेरी गणित की परीक्षा है।': 'my math exam have',
    'गृहकार्य पूरा हो गया है।': 'homework finish',
    'शिक्षक आज अनुपस्थित हैं।': 'teacher today absent',
    'किताब मेज पर है।': 'book table up',
    'मुझे एक पेन उधार चाहिए।': 'pen one borrow need',
    'कॉलेज की फीस कितनी है?': 'college fees how-much',
    'मैं आईएसएल सीख रहा हूँ।': 'me isl learn',
    'क्या आपके पास नोट्स हैं?': 'notes have you',
    'पास होने के लिए कितने अंक चाहिए?': 'pass marks need how-many',
    'इस शर्ट की कीमत क्या है?': 'this shirt price what',
    'यह बहुत महंगा है।': 'this expensive very',
    'क्या इस पर कोई छूट है?': 'discount have',
    'मुझे सब्जियां खरीदनी हैं।': 'me vegetables buy need',
    'दुकान बंद है।': 'shop closed',
    'मुझे रसीद चाहिए।': 'me receipt want',
    'क्या आप ऑनलाइन पेमेंट लेते हैं?': 'online payment accept you',
    'कपड़े की क्वालिटी अच्छी है।': 'cloth quality good',
    'यह साइज बहुत छोटा है।': 'this size small too-much',
    'मुझे पैसे वापस चाहिए।': 'me money return need',
    'आज बहुत गर्मी है।': 'today hot very',
    'बाहर बारिश हो रही है।': 'outside rain happening',
    'कल बहुत ठंड थी।': 'yesterday cold very',
    'तेज हवा चल रही है।': 'wind strong blowing',
    'आसमान में बादल हैं।': 'sky clouds have',
    'छाता मत भूलना।': 'umbrella forget don\'t',
    'धूप बहुत तेज है।': 'sunlight strong',
    'मौसम कल साफ रहेगा।': 'tomorrow weather clear will-be',
    'नदी गहरी है।': 'river deep',
    'बाढ़ आ गई है।': 'flood arrive',
    'चाबी कहाँ रखी है?': 'key where',
    'दरवाजा बंद करो।': 'door close',
    'लाइट चली गई है।': 'electricity gone',
    'पंखा चालू करो।': 'fan on',
    'नल से पानी टपक रहा है।': 'tap water dripping',
    'झाड़ू कहाँ है?': 'broom where',
    'कपड़े सुखा दो।': 'clothes dry put',
    'फोन की बैटरी खत्म हो गई है।': 'phone battery dead',
    'मुझे घर जाना है।': 'me home go need',
    'कूड़ा बाहर फेंक दो।': 'garbage outside throw',
    'पास का बैंक कहाँ है?': 'near bank where',
    'मुझे पैसे निकालने हैं।': 'me money withdraw need',
    'एटीएम काम नहीं कर रहा है।': 'atm work not',
    'आधार कार्ड की फोटोकॉपी चाहिए।': 'aadhaar card xerox need',
    'पुलिस स्टेशन कहाँ है?': 'police station where',
    'मेरा बटुआ चोरी हो गया।': 'my wallet stolen',
    'सरकारी दफ्तर आज बंद है।': 'government office today closed',
    'खाता खुलवाना है।': 'account open need',
    'साइन यहाँ करना है।': 'sign here do',
    'फॉर्म जमा कर दिया है।': 'form submit finish',
  };

  static const tamilPhrases = {
    'எனக்கு ஒரு கப் டீ வேண்டும்.': 'me one cup chai want',
    'இங்கே சைவ உணவு இருக்கிறதா?': 'here vegetarian food have',
    'சாப்பாடு ரொம்ப காரமாக இருக்கிறது.': 'food spicy very',
    'பில் கொண்டு வாருங்கள்.': 'bill bring please',
    'நான் மதிய உணவு சாப்பிடவில்லை.': 'me lunch eat not',
    'தண்ணீர் சுடுதண்ணீரா அல்லது குளிர்ந்த தண்ணீரா?': 'water hot cold which',
    'எனக்கு தோசை பிடிக்கும்.': 'me dosa like',
    'சர்க்கரை எங்கே இருக்கிறது?': 'sugar where',
    'நாளை நாம் ஹோட்டலுக்கு போவோம்.': 'tomorrow we restaurant go',
    'சாப்பாடு கெட்டுப்போய்விட்டது.': 'food spoiled',
    'உங்கள் பெயர் என்ன?': 'your name what',
    'என் பெயர் ஆனந்த்.': 'my name fs-anand',
    'உங்களுக்கு எத்தனை சகோதரர்கள்?': 'your brothers how-many',
    'என் அம்மா ஒரு ஆசிரியர்.': 'my mother teacher',
    'இவன் என் தம்பி.': 'this my brother small',
    'நீங்கள் எங்கே வசிக்கிறீர்கள்?': 'you live where',
    'நான் சென்னையில் வசிக்கிறேன்.': 'me chennai live',
    'உங்களுக்கு திருமணமாகிவிட்டதா?': 'you married',
    'இன்று என் நண்பனின் பிறந்தநாள்.': 'today my friend birthday',
    'என் அப்பா நேற்று வந்தார்.': 'yesterday my father arrive',
    'ரயில் நிலையம் எங்கே இருக்கிறது?': 'railway station where',
    'சென்னை ரயில் எப்போது வரும்?': 'chennai train arrive when',
    'எனக்கு ஒரு ஆட்டோ வேண்டும்.': 'me auto need',
    'டிக்கெட் விலை எவ்வளவு?': 'ticket cost how-much',
    'நான் பஸ்ஸை தவறவிட்டுவிட்டேன்.': 'me bus missed',
    'ரோடு ரொம்ப மோசமாக இருக்கிறது.': 'road bad very',
    'ஏர்போர்ட் தூரமாக இருக்கிறது.': 'airport far',
    'இந்த பஸ் மதுரைக்கு போகுமா?': 'this bus madurai go',
    'என் கார் பழுதாகிவிட்டது.': 'my car broken',
    'எனக்கு ஜன்னல் சீட் வேண்டும்.': 'me window seat want',
    'எனக்கு வயிற்று வலி இருக்கிறது.': 'my stomach hurt',
    'டாக்டர் எப்போது வருவார்?': 'doctor arrive when',
    'எனக்கு கடுமையான காய்ச்சல் இருக்கிறது.': 'me fever high',
    'மருத்துவமனை எங்கே இருக்கிறது?': 'hospital where',
    'இந்த மாத்திரையை ஒரு நாளைக்கு இரண்டு முறை சாப்பிட வேண்டும்.': 'medicine day two times take',
    'எனக்கு தலைச்சுற்றலாக இருக்கிறது.': 'me dizzy',
    'ஆம்புலன்ஸை கூப்பிடுங்கள்!': 'ambulance call quick',
    'அடி பட்டுவிட்டதா?': 'injury have',
    'என் கால் வீங்கியிருக்கிறது.': 'my leg swelling',
    'இரத்தப் பரிசோதனை செய்ய வேண்டும்.': 'me blood test need',
    'மேலாளர் எங்கே?': 'manager where',
    'நாளை காலை 10 மணிக்கு மீட்டிங் இருக்கிறது.': 'tomorrow meeting morning 10-o\'clock',
    'எனக்கு வேலை அதிகமாக இருக்கிறது.': 'me work much',
    'கம்ப்யூட்டர் வேலை செய்யவில்லை.': 'computer work not',
    'இன்று எனக்கு லீவு.': 'today my holiday',
    'இந்த பேப்பரில் கையெழுத்து போடுங்கள்.': 'this paper sign please',
    'இன்டர்வியூ நன்றாக நடந்தது.': 'interview good',
    'எனக்கு மின்னஞ்சல் அனுப்புங்கள்.': 'me email send',
    'சனிக்கிழமை ஆபீஸ் லீவு.': 'office saturday closed',
    'எனக்கு சம்பளம் வந்துவிட்டது.': 'me salary receive',
    'பள்ளி எப்போது திறக்கும்?': 'school open when',
    'எனக்கு கணித தேர்வு இருக்கிறது.': 'my math exam have',
    'வீட்டுப்பாடம் முடிந்துவிட்டது.': 'homework finish',
    'இன்று ஆசிரியர் வரவில்லை.': 'teacher today absent',
    'புத்தகம் மேஜை மேல் இருக்கிறது.': 'book table up',
    'ஒரு பேனா கடன் கொடுங்கள்.': 'pen one borrow need',
    'கல்லூரி கட்டணம் எவ்வளவு?': 'college fees how-much',
    'நான் இந்திய சைகை மொழி படிக்கிறேன்.': 'me isl learn',
    'உங்களிடம் குறிப்புகள் இருக்கிறதா?': 'notes have you',
    'பாஸ் மார்க் எவ்வளவு?': 'pass marks need how-many',
    'இந்த சட்டையின் விலை என்ன?': 'this shirt price what',
    'இது விலை அதிகம்.': 'this expensive very',
    'தள்ளுபடி ஏதேனும் இருக்கிறதா?': 'discount have',
    'நான் காய்கறிகள் வாங்க வேண்டும்.': 'me vegetables buy need',
    'கடை மூடியிருக்கிறது.': 'shop closed',
    'எனக்கு பற்றுச்சீட்டு வேண்டும்.': 'me receipt want',
    'ஆன்லைன் பேமெண்ட் ஏற்குமா?': 'online payment accept you',
    'துணி தரம் நன்றாக உள்ளது.': 'cloth quality good',
    'இந்த அளவு சிறியதாக உள்ளது.': 'this size small too-much',
    'எனக்கு பணம் திரும்ப வேண்டும்.': 'me money return need',
    'இன்று வெயில் அதிகமாக உள்ளது.': 'today hot very',
    'வெளியே மழை பெய்கிறது.': 'outside rain happening',
    'நேற்று குளிராக இருந்தது.': 'yesterday cold very',
    'காற்று பலமாக வீசுகிறது.': 'wind strong blowing',
    'மேகமூட்டமாக உள்ளது.': 'sky clouds have',
    'குடையை மறந்துவிடாதீர்கள்.': 'umbrella forget don\'t',
    'வெயில் கொடுமையாக உள்ளது.': 'sunlight strong',
    'நாளை வானிலை சீராக இருக்கும்.': 'tomorrow weather clear will-be',
    'ஆறு ஆழமானது.': 'river deep',
    'வெள்ளம் வந்துவிட்டது.': 'flood arrive',
    'சாவி எங்கே?': 'key where',
    'கதவை மூடு.': 'door close',
    'கரண்ட் போய்விட்டது.': 'electricity gone',
    'ஃபேனை போடு.': 'fan on',
    'குழாயில் தண்ணீர் ஒழுகுகிறது.': 'tap water dripping',
    'துடைப்பம் எங்கே?': 'broom where',
    'துணிகளை காயப்போடு.': 'clothes dry put',
    'போனில் சார்ஜ் இல்லை.': 'phone battery dead',
    'நான் வீட்டுக்கு போக வேண்டும்.': 'me home go need',
    'குப்பையை வெளியே போடு.': 'garbage outside throw',
    'அருகில் வங்கி எங்கே உள்ளது?': 'near bank where',
    'நான் பணம் எடுக்க வேண்டும்.': 'me money withdraw need',
    'ஏடிஎம் வேலை செய்யவில்லை.': 'atm work not',
    'ஆதார் கார்டு ஜெராக்ஸ் வேண்டும்.': 'aadhaar card xerox need',
    'காவல் நிலையம் எங்கே இருக்கிறது?': 'police station where',
    'என் பர்ஸ் திருடப்பட்டுவிட்டது.': 'my wallet stolen',
    'அரசு அலுவலகம் இன்று விடுமுறை.': 'government office today closed',
    'புதிய கணக்கு தொடங்க வேண்டும்.': 'account open need',
    'இங்கே கையெழுத்திட வேண்டும்.': 'sign here do',
    'படிவம் சமர்ப்பிக்கப்பட்டுவிட்டது.': 'form submit finish',
  };

  static const malayalamPhrases = {
    'എനിക്ക് ഒരു കപ്പ് ചായ വേണം.': 'me one cup chai want',
    'ഇവിടെ വെജിറ്റേറിയൻ ഭക്ഷണം ഉണ്ടോ?': 'here vegetarian food have',
    'ഭക്ഷണത്തിന് നല്ല എരിവുണ്ട്.': 'food spicy very',
    'ബില്ല് കൊണ്ടുവരൂ.': 'bill bring please',
    'ഞാൻ ഉച്ചഭക്ഷണം കഴിച്ചില്ല.': 'me lunch eat not',
    'വെള്ളം ചൂടുള്ളതാണോ തണുത്തതാണോ?': 'water hot cold which',
    'എനിക്ക് ദോശ ഇഷ്ടമാണ്.': 'me dosa like',
    'പഞ്ചസാര എവിടെയാണ് ഇരിക്കുന്നത്?': 'sugar where',
    'നാളെ നമുക്ക് ഹോട്ടലിൽ പോകാം.': 'tomorrow we restaurant go',
    'ഭക്ഷണം കേടായിപ്പോയി.': 'food spoiled',
    'നിങ്ങളുടെ പേരെന്താണ്?': 'your name what',
    'എന്റെ പേര് വിനു എന്നാണ്.': 'my name fs-vinu',
    'നിങ്ങൾക്ക് എത്ര സഹോദരങ്ങളുണ്ട്?': 'your siblings how-many',
    'എന്റെ അമ്മ അധ്യാപികയാണ്.': 'my mother teacher',
    'ഇവൻ എന്റെ അനിയനാണ്.': 'this my brother small',
    'നിങ്ങൾ എവിടെയാണ് താമസിക്കുന്നത്?': 'you live where',
    'ഞാൻ കൊച്ചിയിലാണ് താമസിക്കുന്നത്.': 'me kochi live',
    'നിങ്ങൾ വിവാഹിതനാണോ?': 'you married',
    'ഇന്ന് എന്റെ സുഹൃത്തിന്റെ ജന്മദിനമാണ്.': 'today my friend birthday',
    'എന്റെ അച്ഛൻ ഇന്നലെ വന്നു.': 'yesterday my father arrive',
    'റെയിൽവേ സ്റ്റേഷൻ എവിടെയാണ്?': 'railway station where',
    'കൊച്ചിയിലേക്കുള്ള ട്രെയിൻ എപ്പോഴാണ് വരുക?': 'kochi train arrive when',
    'എനിക്ക് ഒരു ഓട്ടോ വേണം.': 'me auto need',
    'ടിക്കറ്റ് നിരക്ക് എത്രയാണ്?': 'ticket cost how-much',
    'എനിക്ക് ബസ് നഷ്ടപ്പെട്ടു.': 'me bus missed',
    'റോഡ് വളരെ മോശമാണ്.': 'road bad very',
    'എയർപോർട്ട് ദൂരെയാണ്.': 'airport far',
    'ഈ ബസ് തിരുവനന്തപുരത്തേക്ക് പോകുമോ?': 'this bus trivandrum go',
    'എന്റെ കാർ കേടായി.': 'my car broken',
    'എനിക്ക് വിൻഡോ സീറ്റ് വേണം.': 'me window seat want',
    'എനിക്ക് വയറുവേദനയുണ്ട്.': 'my stomach hurt',
    'ഡോക്ടർ എപ്പോൾ വരും?': 'doctor arrive when',
    'എനിക്ക് കടുത്ത പനിയുണ്ട്.': 'me fever high',
    'ആശുപത്രി എവിടെയാണ്?': 'hospital where',
    'ഈ ഗുളിക ദിവസത്തിൽ രണ്ടുതവണ കഴിക്കണം.': 'medicine day two times take',
    'എനിക്ക് തലകറക്കം തോന്നുന്നു.': 'me dizzy',
    'ആംബുലൻസ് വിളിക്കൂ!': 'ambulance call quick',
    'എനിക്ക് പരിക്കേറ്റിട്ടുണ്ടോ?': 'injury have',
    'എന്റെ കാലിൽ നീരുണ്ട്.': 'my leg swelling',
    'രക്തപരിശോധന നടത്തണം.': 'me blood test need',
    'മാനേജർ എവിടെ?': 'manager where',
    'നാളെ രാവിലെ 10 മണിക്ക് മീറ്റിംഗ് ഉണ്ട്.': 'tomorrow meeting morning 10-o\'clock',
    'എനിക്ക് ജോലി കൂടുതലുണ്ട്.': 'me work much',
    'കമ്പ്യൂട്ടർ പ്രവർത്തിക്കുന്നില്ല.': 'computer work not',
    'ഇന്ന് എനിക്ക് അവധിയാണ്.': 'today my holiday',
    'ദയവായി ഈ പേപ്പറിൽ ഒപ്പിടൂ.': 'this paper sign please',
    'ഇന്റർവ്യൂ നന്നായിരുന്നു.': 'interview good',
    'എനിക്ക് ഇമെയിൽ അയക്കൂ.': 'me email send',
    'ശനിയാഴ്ച ഓഫീസ് അവധിയാണ്.': 'office saturday closed',
    'എനിക്ക് ശമ്പളം കിട്ടി.': 'me salary receive',
    'സ്കൂൾ എന്ന് തുറക്കും?': 'school open when',
    'എനിക്ക് കണക്ക് പരീക്ഷയുണ്ട്.': 'my math exam have',
    'ഹോംവർക്ക് തീർന്നു.': 'homework finish',
    'ഇന്ന് ടീച്ചർ വന്നിട്ടില്ല.': 'teacher today absent',
    'പുസ്തകം മേശപ്പുറത്തുണ്ട്.': 'book table up',
    'എനിക്ക് ഒരു പേന കടം തരുമോ?': 'pen one borrow need',
    'കോളേജ് ഫീസ് എത്രയാണ്?': 'college fees how-much',
    'ഞാൻ ഇന്ത്യൻ ആംഗ്യഭാഷ പഠിക്കുകയാണ്.': 'me isl learn',
    'നിങ്ങളുടെ കൈയിൽ നോട്ട്സ് ഉണ്ടോ?': 'notes have you',
    'പാസ് മാർക്ക് എത്രയാണ്?': 'pass marks need how-many',
    'ഈ ഷർട്ടിന്റെ വില എത്രയാണ്?': 'this shirt price what',
    'ഇതിന് വില കൂടുതലാണ്.': 'this expensive very',
    'ഡിസ്കൗണ്ട് വല്ലതുമുണ്ടോ?': 'discount have',
    'എനിക്ക് പച്ചക്കറികൾ വാങ്ങണം.': 'me vegetables buy need',
    'കട അടച്ചിരിക്കുകയാണ്.': 'shop closed',
    'എനിക്ക് ബിൽ വേണം.': 'me receipt want',
    'ഓൺലൈൻ പേയ്മെന്റ് സ്വീകരിക്കുമോ?': 'online payment accept you',
    'തുണിയുടെ ക്വാളിറ്റി നല്ലതാണ്.': 'cloth quality good',
    'ഈ സൈസ് വളരെ ചെറുതാണ്.': 'this size small too-much',
    'എനിക്ക് പണം തിരികെ വേണം.': 'me money return need',
    'ഇന്ന് നല്ല ചൂടാണ്.': 'today hot very',
    'പുറത്ത് മഴ പെയ്യുന്നുണ്ട്.': 'outside rain happening',
    'ഇന്നലെ നല്ല തണുപ്പായിരുന്നു.': 'yesterday cold very',
    'ശക്തമായ കാറ്റടിക്കുന്നുണ്ട്.': 'wind strong blowing',
    'ആകാശം മേഘാവൃതമാണ്.': 'sky clouds have',
    'കുട എടുക്കാൻ മറക്കരുത്.': 'umbrella forget don\'t',
    'വെയിൽ കഠിനമാണ്.': 'sunlight strong',
    'നാളെ കാലാവസ്ഥ തെളിഞ്ഞതായിരിക്കും.': 'tomorrow weather clear will-be',
    'പുഴയ്ക്ക് നല്ല ആഴമുണ്ട്.': 'river deep',
    'വെള്ളപ്പൊക്കം ഉണ്ടായിട്ടുണ്ട്.': 'flood arrive',
    'താക്കോൽ എവിടെയാണ് വെച്ചിരിക്കുന്നത്?': 'key where',
    'വാതിൽ അടയ്ക്കൂ.': 'door close',
    'കറണ്ട് പോയി.': 'electricity gone',
    'ഫാൻ ഓൺ ചെയ്യൂ.': 'fan on',
    'ടാപ്പിൽ നിന്ന് വെള്ളം ഒലിക്കുന്നു.': 'tap water dripping',
    'ചൂൽ എവിടെയാണ്?': 'broom where',
    'വസ്ത്രങ്ങൾ ഉണക്കാൻ ഇടൂ.': 'clothes dry put',
    'ഫോണിൽ ചാർജ് തീർന്നു.': 'phone battery dead',
    'എനിക്ക് വീട്ടിൽ പോകണം.': 'me home go need',
    'മാലിന്യം പുറത്ത് കളയൂ.': 'garbage outside throw',
    'അടുത്തുള്ള ബാങ്ക് എവിടെയാണ്?': 'near bank where',
    'എനിക്ക് പണം പിൻവലിക്കണം.': 'me money withdraw need',
    'എടിഎം വർക്ക് ചെയ്യുന്നില്ല.': 'atm work not',
    'ആധാർ കാർഡിന്റെ സിറോക്സ് വേണം.': 'aadhaar card xerox need',
    'പോലീസ് സ്റ്റേഷൻ എവിടെയാണ്?': 'police station where',
    'എന്റെ പഴ്സ് മോഷണം പോയി.': 'my wallet stolen',
    'സർക്കാർ ഓഫീസ് ഇന്ന് അവധിയാണ്.': 'government office today closed',
    'അക്കൗണ്ട് തുടങ്ങണം.': 'account open need',
    'ഇവിടെ ഒപ്പിടണം.': 'sign here do',
    'ഫോം സമർപ്പിച്ചു കഴിഞ്ഞു.': 'form submit finish',
  };
}
