/// Maps ISL grammar gloss labels to bundled ISL video manifest keys.
abstract final class IslVideoGlossAliases {
  static const toManifestKey = <String, String>{
    '10-o_clock': 'time',
    '10_o_clock': 'time',
    'aadhaar': 'document',
    'absent': 'cannot',
    'accept': 'yes',
    'account': 'bank',
    'arrive': 'come',
    'atm': 'bank',
    'auto': 'car',
    'bill': 'money',
    'birthday': 'happy_birthday',
    'blood': 'item',
    'blowing': 'wind',
    'borrow': 'need',
    'bring': 'carry',
    'broom': 'clean',
    'brothers': 'brother',
    'card': 'credit_card',
    'chai': 'tea',
    'chennai': 'city',
    'clear': 'clean',
    'closed': 'close',
    'clouds': 'cloud',
    'cup': 'item',
    'deep_far': 'far',
    'delhi': 'city',
    'discount': 'cheap',
    'dizzy': 'tired',
    'do': 'work',
    'dont': 'cannot',
    'dripping': 'water',
    'dry': 'clean',
    'electricity': 'light',
    'fan': 'wind',
    'fees': 'money',
    'flood': 'rain',
    'form': 'document',
    'garbage': 'dirty',
    'gone': 'lost',
    'government': 'office',
    'happening': 'rain',
    'have': 'know',
    'high': 'huge',
    'holiday': 'week',
    'how-many': 'how_many',
    'how-much': 'how_much',
    'how_many': 'how_many',
    'how_much': 'how_much',
    'hurt': 'pain',
    'interview': 'meeting',
    'isl': 'learn',
    'kochi': 'city',
    'leg': 'item',
    'live': 'home',
    'madurai': 'city',
    'marks': 'study',
    'married': 'husband',
    'math': 'study',
    'me': 'i',
    'missed': 'late',
    'much': 'more',
    'mumbai': 'city',
    'name': 'what',
    'not': 'cannot',
    'notes': 'message',
    'one': 'item',
    'online': 'internet',
    'paper': 'document',
    'pass': 'go',
    'payment': 'pay',
    'pen': 'write',
    'police': 'police',
    'put': 'carry',
    'quality': 'good',
    'railway': 'train',
    'receipt': 'document',
    'restaurant': 'hotel',
    'river': 'water',
    'salary': 'money',
    'samosa': 'food',
    'saturday': 'week',
    'seat': 'chair',
    'siblings': 'brother',
    'sign': 'write',
    'size': 'small',
    'sky': 'cloud',
    'spicy': 'hot',
    'spoiled': 'bad',
    'stolen': 'lost',
    'stomach': 'pain',
    'submit': 'send',
    'swelling': 'pain',
    'take': 'carry',
    'tap': 'water',
    'test': 'item',
    'this': 'it',
    'times': 'time',
    'two': 'item',
    'umbrella': 'rain',
    'vegetarian': 'vegetable',
    'very': 'big',
    'weather': 'cloud',
    'will_be': 'future',
    'window': 'open',
    'withdraw': 'money',
  };

  static String? manifestKeyFor(String rawKey) {
    final key = rawKey.trim().toLowerCase().replaceAll('-', '_');
    final stripped = key.replaceAll(RegExp(r'[?!]+$'), '');
    return toManifestKey[stripped] ?? toManifestKey[key];
  }
}
