/// Localized phrase text for display and TTS.
abstract final class PhraseLocalizations {
  static const _byId = <String, Map<String, String>>{
    'em_assistance': {
      'ENG': 'I need assistance',
      'ML': 'എനിക്ക് assistance വേണം',
      'HI': 'मुझे सहायता चाहिए',
      'TA': 'எனக்கு உதவி தேवை',
    },
    'em_call_emergency': {
      'ENG': 'Call emergency services',
      'ML': 'emergency services വിളിക്കുക',
      'HI': 'emergency services को call करें',
      'TA': 'emergency services-ஐ அழைக்கவும்',
    },
    'em_call_family': {
      'ENG': 'Please call my family',
      'ML': 'ദയവായി എന്റെ കുടുംബത്തെ വിളിക്കുക',
      'HI': 'कृपया मेरे परिवार को call करें',
      'TA': 'தயவுசெய்து என் குடும்பத்தை அழைக்கவும்',
    },
    'em_cannot_hear': {
      'ENG': 'I cannot hear',
      'ML': 'എനിക്ക് കേൾക്കാൻ കഴിയില്ല',
      'HI': 'मैं सुन नहीं सकता',
      'TA': 'எனக்கு கேட்க முடியாது',
    },
    'em_cannot_speak': {
      'ENG': 'I cannot speak',
      'ML': 'എനിക്ക് സംസാരിക്കാൻ കഴിയില്ല',
      'HI': 'मैं बोल नहीं सकता',
      'TA': 'எனக்கு பேச முடியாது',
    },
    'em_danger': {
      'ENG': 'Danger!',
      'ML': 'അപായം!',
      'HI': 'खतरा!',
      'TA': 'ஆபத்து!',
    },
    'em_evacuate': {
      'ENG': 'Please evacuate',
      'ML': 'ദയവായി evacuate ചെയ്യുക',
      'HI': 'कृपया evacuate करें',
      'TA': 'தயவுசெய்து evacuate செய்யுங்கள்',
    },
    'em_fire': {
      'ENG': 'Fire!',
      'ML': 'തീ!',
      'HI': 'आग!',
      'TA': 'தீ!',
    },
    'em_help': {
      'ENG': 'Help!',
      'ML': 'സഹായം!',
      'HI': 'मदद!',
      'TA': 'உதவி!',
    },
    'em_help_now': {
      'ENG': 'I need help now',
      'ML': 'എനിക്ക് ഇപ്പോൾ സഹായം വേണം',
      'HI': 'मुझे अभी मदद चाहिए',
      'TA': 'எனக்கு இப்போது உதவி தேவை',
    },
    'em_help_please': {
      'ENG': 'Help me please',
      'ML': 'ദയവായി എന്നെ സഹായിക്കുക',
      'HI': 'कृपया मेरी मदद करें',
      'TA': 'தயவுசெய்து எனக்கு உதவுங்கள்',
    },
    'em_hurt': {
      'ENG': 'Someone is hurt',
      'ML': 'ആരോ പരിക്കേറ്റു',
      'HI': 'किसी को चोट लगी है',
      'TA': 'யாரோ காயமடைந்துள்ளார்',
    },
    'em_in_danger': {
      'ENG': 'I am in danger',
      'ML': 'ഞാൻ അപായത്തിലാണ്',
      'HI': 'मैं खतरे में हूँ',
      'TA': 'நான் ஆபத்தில் இருக்கிறேன்',
    },
    'em_lost': {
      'ENG': 'I am lost',
      'ML': 'ഞാൻ നഷ്ടപ്പെട്ടു',
      'HI': 'मैं खो गया हूँ',
      'TA': 'நான் வழி தவறினேன்',
    },
    'em_med_emergency': {
      'ENG': 'Medical emergency',
      'ML': 'medical emergency',
      'HI': 'medical emergency',
      'TA': 'medical emergency',
    },
    'em_police': {
      'ENG': 'Call the police',
      'ML': 'പോലീസ് വിളിക്കുക',
      'HI': 'पुलिस बुलाएँ',
      'TA': 'போலீஸை அழைக்கவும்',
    },
    'em_sos': {
      'ENG': 'SOS',
      'ML': 'SOS',
      'HI': 'SOS',
      'TA': 'SOS',
    },
    'em_stay': {
      'ENG': 'Please stay with me',
      'ML': 'ദയവായി എന്നോട് കൂടെ നിൽക്കുക',
      'HI': 'कृपया मेरे साथ रहें',
      'TA': 'தயவுசெய்து என்னுடன் இருங்கள்',
    },
    'em_translator': {
      'ENG': 'I need a translator',
      'ML': 'എനിക്ക് translator വേണം',
      'HI': 'मुझे translator चाहिए',
      'TA': 'எனக்கு translator தேवை',
    },
    'em_where_am_i': {
      'ENG': 'Where am I?',
      'ML': 'ഞാൻ എവിടെയാണ്?',
      'HI': 'मैं कहाँ हूँ?',
      'TA': 'நான் எங்கே?',
    },
    'greet_deaf_mute': {
      'ENG': 'I am deaf / mute',
      'ML': 'ഞാൻ ബധിരനാണ് / മൂകനാണ്',
      'HI': 'मैं बहरा / मूक हूँ',
      'TA': 'நான் செவிடர் / ஊமை',
    },
    'greet_dont_understand': {
      'ENG': "I don't understand",
      'ML': 'എനിക്ക് മനസ്സിലാകുന്നില്ല',
      'HI': 'मुझे समझ नहीं आया',
      'TA': 'எனக்கு புரியவில்லை',
    },
    'greet_evening': {
      'ENG': 'Good evening',
      'ML': 'ശുഭ സായാഹ്നം',
      'HI': 'शुभ संध्या',
      'TA': 'மாலை வணக்கம்',
    },
    'greet_excuse_me': {
      'ENG': 'Excuse me',
      'ML': 'ക്ഷമിക്കണം',
      'HI': 'माफ़ कीजिए',
      'TA': 'மன்னிக்கவும்',
    },
    'greet_goodbye': {
      'ENG': 'Goodbye',
      'ML': 'വിട',
      'HI': 'अलविदा',
      'TA': 'பிரியாவிடை',
    },
    'greet_hello': {
      'ENG': 'Hello',
      'ML': 'നമസ്കാരം',
      'HI': 'नमस्ते',
      'TA': 'வணக்கம்',
    },
    'greet_how_are_you': {
      'ENG': 'How are you?',
      'ML': 'സുഖമാണോ?',
      'HI': 'आप कैसे हैं?',
      'TA': 'எப்படி இருக்கிறீர்கள்?',
    },
    'greet_morning': {
      'ENG': 'Good morning',
      'ML': 'സുപ്രഭാതം',
      'HI': 'सुप्रभात',
      'TA': 'காலை வணக்கம்',
    },
    'greet_my_name': {
      'ENG': 'My name is',
      'ML': 'എന്റെ പേര്',
      'HI': 'मेरा नाम',
      'TA': 'என் பெயர்',
    },
    'greet_nice_meet': {
      'ENG': 'Nice to meet you',
      'ML': 'നിങ്ങളെ കാണാനായി സന്തോഷം',
      'HI': 'आपसे मिलकर खुशी हुई',
      'TA': 'உங்களை சந்தித்ததில் மகிழ்ச்சி',
    },
    'greet_no': {
      'ENG': 'No',
      'ML': 'അല്ല',
      'HI': 'नहीं',
      'TA': 'இல்லை',
    },
    'greet_please_wait': {
      'ENG': 'Please wait',
      'ML': 'ദയവായി കാത്തിരിക്കുക',
      'HI': 'कृपया प्रतीक्षा करें',
      'TA': 'தயவுசெய்து காத்திருங்கள்',
    },
    'greet_repeat': {
      'ENG': 'Can you repeat that?',
      'ML': 'ദയവായി വീണ്ടും പറയുക',
      'HI': 'कृपया दोहराएँ',
      'TA': 'தயவுசெய்து மீண்டும் சொல்லுங்கள்',
    },
    'greet_see_you': {
      'ENG': 'See you later',
      'ML': 'പിന്നീട് കാണാം',
      'HI': 'फिर मिलेंगे',
      'TA': 'பிறகு சந்திப்போம்',
    },
    'greet_slowly': {
      'ENG': 'Please speak slowly',
      'ML': 'ദയവായി slowly പറയുക',
      'HI': 'कृपया धीरे बोलें',
      'TA': 'தயவுசெய்து மெதுவாகச் சொல்லுங்கள்',
    },
    'greet_sorry': {
      'ENG': 'Sorry',
      'ML': 'ക്ഷമിക്കണം',
      'HI': 'माफ़ करें',
      'TA': 'மன்னிக்கவும்',
    },
    'greet_thanks': {
      'ENG': 'Thank you',
      'ML': 'നന്ദി',
      'HI': 'धन्यवाद',
      'TA': 'நன்றி',
    },
    'greet_welcome': {
      'ENG': "You're welcome",
      'ML': 'സ്വാഗതം',
      'HI': 'आपका स्वागत है',
      'TA': 'வரவேற்கிறோம்',
    },
    'greet_write_down': {
      'ENG': 'Please write it down',
      'ML': 'ദയവായി എഴുതിക്കൊടുക്കുക',
      'HI': 'कृपया लिखकर दें',
      'TA': 'தயவுசெய்து எழுதிக் காட்டுங்கள்',
    },
    'greet_yes': {
      'ENG': 'Yes',
      'ML': 'അതെ',
      'HI': 'हाँ',
      'TA': 'ஆம்',
    },
    'med_accident': {
      'ENG': 'I had an accident',
      'ML': 'എനിക്ക് അപകടം സംഭവിച്ചു',
      'HI': 'मेरा accident हुआ',
      'TA': 'எனக்கு விபத்து நேர்ந்தது',
    },
    'med_allergic_to': {
      'ENG': 'I am allergic to',
      'ML': 'എനിക്ക് അലർജിയുണ്ട്',
      'HI': 'मुझे allergy है',
      'TA': 'எனக்கு allergy உள்ளது',
    },
    'med_allergy': {
      'ENG': 'I have an allergy',
      'ML': 'എനിക്ക് അലർജി ഉണ്ട്',
      'HI': 'मुझे एलर्जी है',
      'TA': 'எனக்கு allergy உள்ளது',
    },
    'med_ambulance': {
      'ENG': 'Call an ambulance',
      'ML': 'ആംബുലൻസ് വിളിക്കുക',
      'HI': 'एम्बुलेंस बुलाएँ',
      'TA': 'ஆம்புலன்ஸ் அழைக்கவும்',
    },
    'med_blood_type': {
      'ENG': 'My blood type is',
      'ML': 'എന്റെ രക്തഗ്രൂപ്പ്',
      'HI': 'मेरा रक्त समूह',
      'TA': 'என் இரத்த வகை',
    },
    'med_breathe': {
      'ENG': 'I cannot breathe',
      'ML': 'എനിക്ക് ശ്വാസം കിട്ടുന്നില്ല',
      'HI': 'मुझे साँस नहीं आ रही',
      'TA': 'எனக்கு மூச்சு வரவில்லை',
    },
    'med_chest_pain': {
      'ENG': 'I have chest pain',
      'ML': 'എനിക്ക് നെഞ്ചുവേദനയുണ്ട്',
      'HI': 'मुझे सीने में दर्द है',
      'TA': 'எனக்கு மார்பு வலி',
    },
    'med_diabetic': {
      'ENG': 'I am diabetic',
      'ML': 'ഞാൻ പ്രമേഹ രോഗിയാണ്',
      'HI': 'मैं मधुमेही हूँ',
      'TA': 'நான் நீரிழிவு நோயாளி',
    },
    'med_dizzy': {
      'ENG': 'I feel dizzy',
      'ML': 'എനിക്ക് തലകറക്കമുണ്ട്',
      'HI': 'मुझे चक्कर आ रहा है',
      'TA': 'எனக்கு தலைச்சுற்றல்',
    },
    'med_doctor': {
      'ENG': 'I need a doctor',
      'ML': 'എനിക്ക് ഒരു ഡോക്ടർ വേണം',
      'HI': 'मुझे डॉक्टर चाहिए',
      'TA': 'எனக்கு மருத்துவர் தேவை',
    },
    'med_emergency': {
      'ENG': 'This is a medical emergency',
      'ML': 'ഇത് ഒരു medical emergency ആണ്',
      'HI': 'यह medical emergency है',
      'TA': 'இது medical emergency',
    },
    'med_fever': {
      'ENG': 'I have a fever',
      'ML': 'എനിക്ക് പനിയുണ്ട്',
      'HI': 'मुझे बुखार है',
      'TA': 'எனக்கு காய்ச்சல்',
    },
    'med_help': {
      'ENG': 'I need help',
      'ML': 'എനിക്ക് സഹായം വേണം',
      'HI': 'मुझे मदद चाहिए',
      'TA': 'எனக்கு உதவி தேவை',
    },
    'med_hospital': {
      'ENG': 'Where is the hospital?',
      'ML': 'ആശുപത്രി എവിടെയാണ്?',
      'HI': 'अस्पताल कहाँ है?',
      'TA': 'மருத்துவமனை எங்கே?',
    },
    'med_medication': {
      'ENG': 'I take medication',
      'ML': 'ഞാൻ മരുന്ന് കഴിക്കുന്നു',
      'HI': 'मैं दवा लेता हूँ',
      'TA': 'நான் மருந்து சாப்பிடுகிறேன்',
    },
    'med_pain': {
      'ENG': 'I feel pain here',
      'ML': 'എനിക്ക് ഇവിടെ വേദനയുണ്ട്',
      'HI': 'मुझे यहाँ दर्द है',
      'TA': 'எனக்கு இங்கே வலி',
    },
    'med_pharmacy': {
      'ENG': 'I need a pharmacy',
      'ML': 'എനിക്ക് ഫാർമസി വേണം',
      'HI': 'मुझे फार्मेसी चाहिए',
      'TA': 'எனக்கு மருந்தகம் தேவை',
    },
    'med_pregnant': {
      'ENG': 'I am pregnant',
      'ML': 'ഞാൻ ഗർഭിണിയാണ്',
      'HI': 'मैं गर्भवती हूँ',
      'TA': 'நான் கர்ப்பமாக இருக்கிறேன்',
    },
    'med_sick': {
      'ENG': 'I am sick',
      'ML': 'എനിക്ക് അസുഖമാണ്',
      'HI': 'मैं बीमार हूँ',
      'TA': 'நான் உடம்பு சரியில்லை',
    },
    'med_wheelchair': {
      'ENG': 'I need a wheelchair',
      'ML': 'എനിക്ക് wheelchair വേണം',
      'HI': 'मुझे wheelchair चाहिए',
      'TA': 'எனக்கு wheelchair தேவை',
    },
    'shop_bag': {
      'ENG': 'I need a bag please',
      'ML': 'എനിക്ക് bag വേണം',
      'HI': 'मुझे bag चाहिए',
      'TA': 'எனக்கு bag வேண்டும்',
    },
    'shop_card': {
      'ENG': 'Can I pay by card?',
      'ML': 'card കൊണ്ട് pay ചെയ്യാമോ?',
      'HI': 'card से pay कर सकता हूँ?',
      'TA': 'card-ஆ pay செய்யலாமா?',
    },
    'shop_cash': {
      'ENG': 'Do you accept cash?',
      'ML': 'cash സ്വീകരിക്കുമോ?',
      'HI': 'cash लेते हैं?',
      'TA': 'cash ஏற்றுக்கொள்கிறீர்களா?',
    },
    'shop_cashier': {
      'ENG': 'Where is the cashier?',
      'ML': 'cashier എവിടെ?',
      'HI': 'cashier कहाँ है?',
      'TA': 'cashier எங்கே?',
    },
    'shop_closed': {
      'ENG': 'What time do you close?',
      'ML': 'എപ്പോൾ close ചെയ്യും?',
      'HI': 'कब बंद होता है?',
      'TA': 'எப்போது close?',
    },
    'shop_color': {
      'ENG': 'Do you have this in another color?',
      'ML': 'വേറെ color-ൽ ഉണ്ടോ?',
      'HI': 'दूसरे color में है?',
      'TA': 'வேறு color-ல் உள்ளதா?',
    },
    'shop_cost': {
      'ENG': 'How much does this cost?',
      'ML': 'ഇതിന്റെ വില എത്ര?',
      'HI': 'इसकी कीमत कितनी है?',
      'TA': 'இதன் விலை எவ்வளவு?',
    },
    'shop_discount': {
      'ENG': 'Is there a discount?',
      'ML': 'discount ഉണ്ടോ?',
      'HI': 'discount है?',
      'TA': 'discount உள்ளதா?',
    },
    'shop_expensive': {
      'ENG': 'That is too expensive',
      'ML': 'ഇത് വളരെ costly ആണ്',
      'HI': 'यह बहुत महँगा है',
      'TA': 'இது மிகவும் дорого',
    },
    'shop_fitting': {
      'ENG': 'Where is the fitting room?',
      'ML': 'fitting room എവിടെ?',
      'HI': 'fitting room कहाँ है?',
      'TA': 'fitting room எங்கே?',
    },
    'shop_looking': {
      'ENG': 'I am just looking',
      'ML': 'ഞാൻ просто നോക്കുകയാണ്',
      'HI': 'मैं बस देख रहा हूँ',
      'TA': 'நான் просто பார்க்கிறேன்',
    },
    'shop_open': {
      'ENG': 'Are you open?',
      'ML': 'തുറന്നിട്ടുണ്ടോ?',
      'HI': 'खुला है?',
      'TA': 'திறந்திருக்கிறதா?',
    },
    'shop_receipt': {
      'ENG': 'I need a receipt',
      'ML': 'എനിക്ക് receipt വേണം',
      'HI': 'मुझे receipt चाहिए',
      'TA': 'எனக்கு receipt வேண்டும்',
    },
    'shop_return': {
      'ENG': 'Can I return this?',
      'ML': 'ഇത് return ചെയ്യാമോ?',
      'HI': 'इसे return कर सकता हूँ?',
      'TA': 'இதை return செய்யலாமா?',
    },
    'shop_smaller': {
      'ENG': 'Do you have a smaller size?',
      'ML': 'ചെറിയ size ഉണ്ടോ?',
      'HI': 'छोटा size है?',
      'TA': 'சிறிய size உள்ளதா?',
    },
    'shop_stock': {
      'ENG': 'Is this in stock?',
      'ML': 'stock-ൽ ഉണ്ടോ?',
      'HI': 'stock में है?',
      'TA': 'stock-ல் உள்ளதா?',
    },
    'shop_take_it': {
      'ENG': "I'll take it",
      'ML': 'ഞാൻ ഇത് എടുക്കുന്നു',
      'HI': 'मैं यह लेता हूँ',
      'TA': 'நான் இதை எடுக்கிறேன்',
    },
    'shop_this_one': {
      'ENG': 'I would like this one',
      'ML': 'എനിക്ക് ഇത് വേണം',
      'HI': 'मुझे यह चाहिए',
      'TA': 'எனக்கு இது வேண்டும்',
    },
    'shop_try_on': {
      'ENG': 'Can I try this on?',
      'ML': 'ഇത് try ചെയ്യാമോ?',
      'HI': 'इसे try कर सकता हूँ?',
      'TA': 'இதை try செய்யலாமா?',
    },
    'shop_two': {
      'ENG': 'How much for two?',
      'ML': 'രണ്ടിന് എത്ര?',
      'HI': 'दो का कितना?',
      'TA': 'இரண்டுக்கு எவ்வளவு?',
    },
    'trans_address': {
      'ENG': 'Take me to this address',
      'ML': 'ഈ വിലാസത്തിലേക്ക് കൊണ്ടുപോകുക',
      'HI': 'मुझे इस पते पर ले चलें',
      'TA': 'இந்த முகவரிக்கு கொண்டு செல்லுங்கள்',
    },
    'trans_airport': {
      'ENG': 'Where is the airport?',
      'ML': 'എയർപോർട്ട് എവിടെയാണ്?',
      'HI': 'एयरपोर्ट कहाँ है?',
      'TA': 'விமான நிலையம் எங்கே?',
    },
    'trans_bus_stop': {
      'ENG': 'Where is the bus stop?',
      'ML': 'ബസ് സ്റ്റോപ്പ് എവിടെയാണ്?',
      'HI': 'बस स्टॉप कहाँ है?',
      'TA': 'பஸ் நிறுத்தம் எங்கே?',
    },
    'trans_call_cab': {
      'ENG': 'Please call a cab',
      'ML': 'ദയവായി cab വിളിക്കുക',
      'HI': 'कृपया cab बुलाएँ',
      'TA': 'தயவுசெய்து cab அழைக்கவும்',
    },
    'trans_directions': {
      'ENG': 'I need directions',
      'ML': 'എനിക്ക് directions വേണം',
      'HI': 'मुझे रास्ता बताइए',
      'TA': 'எனக்கு வழி தேவை',
    },
    'trans_exit': {
      'ENG': 'Where is the exit?',
      'ML': 'പുറത്തേക്കുള്ള വഴി എവിടെ?',
      'HI': 'बाहर निकलने का रास्ता कहाँ है?',
      'TA': 'வெளியேறும் வழி எங்கே?',
    },
    'trans_go_straight': {
      'ENG': 'Go straight',
      'ML': 'നേരെ പോകുക',
      'HI': 'सीधे जाएँ',
      'TA': 'நேராகச் செல்லுங்கள்',
    },
    'trans_how_long': {
      'ENG': 'How long will it take?',
      'ML': 'എത്ര സമയം എടുക്കും?',
      'HI': 'कितना समय लगेगा?',
      'TA': 'எவ்வளவு நேரம் ஆகும்?',
    },
    'trans_lost': {
      'ENG': 'I am lost',
      'ML': 'ഞാൻ നഷ്ടപ്പെട്ടു',
      'HI': 'मैं खो गया हूँ',
      'TA': 'நான் வழி தவறினேன்',
    },
    'trans_missed_bus': {
      'ENG': 'I missed my bus',
      'ML': 'എന്റെ ബസ് നഷ്ടപ്പെട്ടു',
      'HI': 'मेरी बस छूट गई',
      'TA': 'என் பஸ் தவறிவிட்டது',
    },
    'trans_one_ticket': {
      'ENG': 'One ticket please',
      'ML': 'ഒരു ടിക്കറ്റ് തരൂ',
      'HI': 'एक टिकट दीजिए',
      'TA': 'ஒரு டிக்கெட் தாருங்கள்',
    },
    'trans_parking': {
      'ENG': 'Where is the parking?',
      'ML': 'പാർക്കിംഗ് എവിടെയാണ്?',
      'HI': 'पार्किंग कहाँ है?',
      'TA': 'பார்க்கிங் எங்கே?',
    },
    'trans_platform': {
      'ENG': 'Which platform?',
      'ML': 'ഏത് platform?',
      'HI': 'कौन सा platform?',
      'TA': 'எந்த platform?',
    },
    'trans_right_bus': {
      'ENG': 'Is this the right bus?',
      'ML': 'ഇതാണോ ശരിയായ ബസ്?',
      'HI': 'क्या यह सही बस है?',
      'TA': 'இதுதான் சரியான பஸா?',
    },
    'trans_stop_here': {
      'ENG': 'Stop here please',
      'ML': 'ഇവിടെ നിർത്തൂ',
      'HI': 'यहाँ रोक दीजिए',
      'TA': 'இங்கே நிறுத்துங்கள்',
    },
    'trans_taxi': {
      'ENG': 'I need a taxi',
      'ML': 'എനിക്ക് ടാക്സി വേണം',
      'HI': 'मुझे taxi चाहिए',
      'TA': 'எனக்கு taxi தேவை',
    },
    'trans_ticket': {
      'ENG': 'How much is the ticket?',
      'ML': 'ടിക്കറ്റ് എത്ര?',
      'HI': 'टिकट कितने का है?',
      'TA': 'டிக்கெட் எவ்வளவு?',
    },
    'trans_train': {
      'ENG': 'Where is the train station?',
      'ML': 'ട്രെയിൻ സ്റ്റേഷൻ എവിടെയാണ്?',
      'HI': 'रेलवे स्टेशन कहाँ है?',
      'TA': 'ரயில் நிலையம் எங்கே?',
    },
    'trans_turn_left': {
      'ENG': 'Turn left',
      'ML': 'ഇടത്തോട്ട് തിരിയുക',
      'HI': 'बाएँ मुड़ें',
      'TA': 'இடதுபுறம் திரும்புங்கள்',
    },
    'trans_turn_right': {
      'ENG': 'Turn right',
      'ML': 'വലത്തോട്ട് തിരിയുക',
      'HI': 'दाएँ मुड़ें',
      'TA': 'வலதுபுறம் திரும்புங்கள்',
    },
  };

  static String text(
    String phraseId,
    String languageCode, {
    required String fallback,
  }) {
    final localized =
        _byId[phraseId]?[languageCode.trim().toUpperCase()];
    if (localized != null && localized.trim().isNotEmpty) {
      return localized;
    }
    return fallback;
  }
}
